const tournamentsData = [
	{
		id: "0097098",
		title: "SoloShowdown Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:00PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/SoloShowdown.png"),
		background: require("../assets/Images/SoloShowdownBackground.png"),
	},
	{
		id: "0097099",
		title: "Arena Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:50PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/Arena.png"),
		background: require("../assets/Images/ArenaBackground.png"),
	},
	{
		id: "0097089",
		title: "Turbo Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:50PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/Turbo.png"),
		background: require("../assets/Images/TurboBackground.png"),
	},
	{
		id: "00970008",
		title: "SoloShowdown Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:00PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/SoloShowdown.png"),
		background: require("../assets/Images/SoloShowdownBackground.png"),
	},
	{
		id: "0097049",
		title: "Arena Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:50PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/Arena.png"),
		background: require("../assets/Images/ArenaBackground.png"),
	},
	{
		id: "0097079",
		title: "Turbo Free",
		game: "League of Legends",
		time: "Tue, Jun 11, 8:50PM",
		prize: "$3",
		scoring: "Best 2 Games",
		bracket: 10,
		duration: "2 hrs",
		entryFee: "Free",
		logo: require("../assets/Images/Turbo.png"),
		background: require("../assets/Images/TurboBackground.png"),
	},
]

export default tournamentsData
